### ISSUE TITLE
Deluge not seeding

### ISSUE THREAD

**Issue by she11sh0cked** [jfroment/seedbox#13] opened 2021-02-19 14:14 UTC
Deluge doesn't seem to be able to seed anything. Probably because of the HTTP auth.

**Comment by she11sh0cked** [comment] 2021-02-19 16:42
I don't really know what the issue with deluge is. I've gotten it to work in the past...
Anyway! This qBittorrent configuration works (somehow), so I'll be using it for now.
```yaml
services:
  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    restart: always
    volumes:
      - configqbittorrent:/config
      - downloadstorrents:/data/downloads/torrents
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - WEBUI_PORT=8181
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.${TRAEFIK_DOMAIN}`)"
      - "traefik.http.services.qbittorrent-seedbox.loadbalancer.server.port=8181"

volumes:
  configqbittorrent: 
    driver: local-persist
    driver_opts:
      mountpoint: /data/config/qbittorrent
  downloadstorrents:
    driver: local-persist
    driver_opts:
      mountpoint: /data/shared/downloads/torrents
```
I would be happy to hear if anyone else has this issue though!

**Comment by jfroment** [comment] 2021-02-21 17:34
That is strange, I never had any issue with Deluge.
Here is my configuration:
![image](https://user-images.githubusercontent.com/2869798/108633182-3689e580-7473-11eb-9a8e-9e3bc7bb086d.png)

Keep in mind that mapping the port with the one on the host exposes your server and increases the attack surface. Normally for seeding torrents you do not need it.

**Comment by jfroment** [comment] 2021-04-28 09:28
I'm closing this issue since I cannot reproduce it.
Feel free to re-open it if you need.

**Closed by jfroment** 2021-04-28 09:28 UTC
