### ISSUE TITLE
Flood won't start

### ISSUE THREAD

**Issue by she11sh0cked** [jfroment/seedbox#20] opened 2021-07-15 12:04 UTC
When starting Flood i get the following error repeatedly:
```
Failed to access runtime directory
```
Appearently this has something to do with permissions? ([see here](https://github.com/jesec/flood#troubleshooting))

---

Just to see what would happen i removed the `--rundir=/config` from `flood.yaml`. This time i get the following error:
```
Flood server 4.6.1 starting on http://0.0.0.0:3000
Starting without builtin authentication
(node:8) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
FATAL internal error. Please open an issue.
Unhandled rejection: undefined
```

At least it's more verbose then the last one, right? :)

---

To Cut a Long Story Short: I wanted to ask if someone came across this whilst setting up the box, and has a solution.

**Comment by she11sh0cked** [comment] 2021-07-15 12:05
To add to this: The config folder for flood exists on the host and is owned by root

**Comment by she11sh0cked** [comment] 2021-07-16 15:38
Ok so the issue was, that `/data/**/*` was owned by root!

**Comment by she11sh0cked** [comment] 2021-07-16 15:41
Still getting the second error though

**Comment by Gyrfalc0n** [comment] 2022-01-30 21:11
I'm getting the same error... Flood container is the only one not starting. A ```docker logs --details container_id``` shows me this : 

![image](https://user-images.githubusercontent.com/46728024/151718005-e39ae402-94cb-4c19-9761-5f811d1ded8f.png)

**Comment by jfroment** [comment] 2022-02-19 11:29
Could you please try the following:

- Stop Flood container
- Delete all the content located in ``/db/_config`` directory (in flood config dir)
- Restart flood

**Comment by jfroment** [comment] 2022-03-07 22:06
Hello,

Any news on this? Can I close this issue?

**Comment by Mrmel94** [comment] 2022-03-08 14:55
> Could you please try the following:
> 
>     * Stop Flood container
> 
>     * Delete all the content located in `/db/_config` directory (in flood config dir)
> 
>     * Restart flood

Not working even with this

**Comment by jfroment** [comment] 2022-03-08 15:02
Could you also try the following:

```sh
docker rm -f flood
source .env
sudo chown -R ${PUID}:${PGUID} /data/config/flood
rm -rf /data/config/flood/*
./update-all.sh # (or ./run-seedbox.sh if migrated to v2)
```

**Comment by Mrmel94** [comment] 2022-03-08 15:16
Same, I even did the installation 3 months ago from scratch and it didn't work.

`dfd68377fcdc   jesec/flood:latest                     "/sbin/tini -- flood…"   About a minute ago   Restarting (1) 6 seconds ago                                                             `

```
[root@MelDock seedbox]# docker logs flood
Flood server 4.7.0 starting on http://0.0.0.0:3000

Starting without builtin authentication

(node:7) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
FATAL internal error. Please open an issue.
Unhandled rejection: undefined
Flood server 4.7.0 starting on http://0.0.0.0:3000
```

**Comment by stroebs** [comment] 2022-04-02 19:02
I am having the same issue. Deluge works fine on its own but Flood can't seem to connect to the Deluge daemon port for whatever reason. Looks to be a problem with the Deluge version that's in use, so perhaps using rTorrent is better until Deluge support is no longer experimental with Flood.

**Comment by stroebs** [comment] 2022-04-03 08:47
Really simple fix @Mrmel94 @jfroment @she11sh0cked @Gyrfalc0n - this is caused by the default Deluge config option `allow_remote` set to false.

Edit `config/deluge/core.conf` and change `"allow_remote": false` to `"allow_remote": true` and Flood will start and be able to access Deluge.

**Comment by jfroment** [comment] 2022-05-17 09:41
Oh yes that's a flag that is required for Flood to work.
I'm keeping this ticket open in order to take it into account in the doc for the next release.

**Closed** 2023-03-14 21:50 UTC
Labels: planned, fixed-and-needs-doc

**Comment by joydashy** [comment] 2024-11-21 16:37
Just wanted to mention that on the latest seedbox release, Deluge still has "allow_remote": false" by default.
